### ISSUE TITLE
why the pageId could be found, but the page couldn't be found?

### ISSUE THREAD

**Issue by juvenilezjp** [dkpro/dkpro-jwpl#143]
```java
private static void DFSCategoryTree(Category category) throws WikiApiException
	{
		// TODO Auto-generated method stub
		if (!vCategories.contains(category.getTitle()))
		{
			System.out.println(category.getTitle());
			System.out.println(category.getNumberOfPages());
			vCategories.add(category);
			for (Integer pageId : category.getArticleIds())
			{
				if (!vPageIds.contains(pageId))
				{
					System.out.println("pageid is :" + pageId);
				}
			}
			for (Page page : category.getArticles())
			{
				if (!vPageIds.contains(page))
				{
					System.out.println("pageid is :" + page);
				}
			}

			for (Category sonCategory : category.getChildren())
			{
				DFSCategoryTree(sonCategory);
			}
		}
		return;
	}
```

output result:

```
2
pageid is :68994
pageid is :4569724
Exception in thread "main" de.tudarmstadt.ukp.wikipedia.api.exception.WikiPageNotFoundException: No page with page id 4569724 was found.
	at de.tudarmstadt.ukp.wikipedia.api.Page.fetchByPageId(Page.java:178)
	at de.tudarmstadt.ukp.wikipedia.api.Page.<init>(Page.java:90)
	at de.tudarmstadt.ukp.wikipedia.api.Wikipedia.getPage(Wikipedia.java:146)
	at de.tudarmstadt.ukp.wikipedia.api.Category.getArticles(Category.java:299)
	at iie.ac.cn.zjp.ShowCategoryInfo.DFSCategoryTree(ShowCategoryInfo.java:76)
	at iie.ac.cn.zjp.ShowCategoryInfo.DFSCategoryTree(ShowCategoryInfo.java:86)
	at iie.ac.cn.zjp.ShowCategoryInfo.DFSCategoryTree(ShowCategoryInfo.java:86)
	at iie.ac.cn.zjp.ShowCategoryInfo.showCategoryInfo(ShowCategoryInfo.java:49)
	at iie.ac.cn.zjp.ShowCategoryInfo.main(ShowCategoryInfo.java:104)
```

**Comment by juvenilezjp** [comment]
And the log says:

"2016.12.21 15:08:35","1027080192","678263864","processing table text..."
"2016.12.21 15:10:06","1029177344","285370688","Text 10000"
"2016.12.21 15:11:02","1031274496","463701288","Text 20000"
"2016.12.21 15:11:38","1031274496","385796456","Text 30000"
.........
"2016.12.21 15:59:06","638058496","262472576","Text 1810000"
"2016.12.21 15:59:22","639107072","266876696","Text 1820000"
"2016.12.21 15:59:36","640155648","293868264","Text 1830000"
"2016.12.21 15:59:49","640679936","196448648","Text 1840000"
"2016.12.21 16:00:02","641728512","268223384","Text 1850000"
"2016.12.21 16:00:13","642252800","213163176","writing metadata..."
"2016.12.21 16:00:13","642252800","213163176","finished"
"2016.12.21 16:00:13","642252800","213163176","End of the application. Working time = 5763189 ms"

Bug I only get 1242768 in the Page.txt

**Comment by daxenberger** [comment]
Maybe this page is from a namespace that is not included in your JWPL database? You can check whether it is in the Page table of your local database. You can you e.g. the [MediaWiki API](https://www.mediawiki.org/wiki/API:Main_page) to get some more meta data (e.g. namespace) about the respective page in case you don't have it in your local database.
