### ISSUE TITLE
Sweble libraries are massively outdated

### ISSUE THREAD

**Issue by tgalery** [dkpro/dkpro-jwpl#152]
This uses `1.1.0`, current version is `3.1.6`

**Comment by tgalery** [comment]
I've been working on the upgrades here https://github.com/tgalery/dkpro-jwpl/tree/sweble . It's currently compiling with all tests passing, but I want to create a class that loads specific language configs instead of the default english one.

**Comment by rzo1** [comment]
I experience issues with this old version on certain (modern) Wikipedia pages. See stacktrace below:

```
Caused by: de.tudarmstadt.ukp.wikipedia.api.exception.WikiApiException: org.sweble.wikitext.engine.CompilerException: Parsing failed!
    at de.tudarmstadt.ukp.wikipedia.api.Page.getCompiledPage(Page.java:632)
    at de.tudarmstadt.ukp.wikipedia.api.Page.parsePage(Page.java:609)
    at de.tudarmstadt.ukp.wikipedia.api.Page.getPlainText(Page.java:590)
    at de.hshn.mi.tulum.graph.wikigraph.service.domain.impl.JWPLPageImpl.getPlainText(JWPLPageImpl.java:92)
    ... 11 more
Caused by: org.sweble.wikitext.engine.CompilerException: Parsing failed!
    at org.sweble.wikitext.engine.Compiler.parse(Compiler.java:684)
    at org.sweble.wikitext.engine.Compiler.postprocess(Compiler.java:290)
    at de.tudarmstadt.ukp.wikipedia.api.Page.getCompiledPage(Page.java:630)
    ... 14 more
Caused by: ParserShouldNotBeHereException: Schamane:220:3: <!> "[[Datei:Map-icon"
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.throwShouldNotBeHereException(LazyRatsParser.java:18460)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pThrowShouldNotBeHereException(LazyRatsParser.java:12783)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pShouldNotBeHere(LazyRatsParser.java:12746)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.p$$Shared11(LazyRatsParser.java:7702)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableBlockCell(LazyRatsParser.java:8381)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableCellTransient(LazyRatsParser.java:8146)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableCellMemoized$1(LazyRatsParser.java:8067)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableCellMemoized(LazyRatsParser.java:8053)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableCell(LazyRatsParser.java:8018)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableRowElement(LazyRatsParser.java:9510)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableRowContentStar(LazyRatsParser.java:9451)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableRowBody(LazyRatsParser.java:9365)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableRowTransient(LazyRatsParser.java:9303)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableRowMemoized$1(LazyRatsParser.java:9247)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableRowMemoized(LazyRatsParser.java:9233)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableRow(LazyRatsParser.java:9198)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableElement(LazyRatsParser.java:6975)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableContentStar(LazyRatsParser.java:6907)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableBody(LazyRatsParser.java:6717)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableTransient(LazyRatsParser.java:6667)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableMemoized$1(LazyRatsParser.java:6632)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTableMemoized(LazyRatsParser.java:6618)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pTable(LazyRatsParser.java:6584)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pLineStartProd(LazyRatsParser.java:642)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pParagraphStopper(LazyRatsParser.java:985)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pInlineTextBlockMore(LazyRatsParser.java:1593)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pInlineTextBlock(LazyRatsParser.java:1504)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pInlineBlockContent(LazyRatsParser.java:1376)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pLinkTitle(LazyRatsParser.java:4695)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pOptionsAndTitle(LazyRatsParser.java:3842)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pInternalLinkChoice(LazyRatsParser.java:3601)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pInternalLinkTransient(LazyRatsParser.java:3530)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pInternalLinkMemoized$1(LazyRatsParser.java:3476)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pInternalLinkMemoized(LazyRatsParser.java:3460)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pInternalLink(LazyRatsParser.java:3425)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pInlineContentAtom(LazyRatsParser.java:1932)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pInlineContentChoice(LazyRatsParser.java:1856)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pInlineContentPlus(LazyRatsParser.java:1701)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pParagraphText(LazyRatsParser.java:1182)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pParagraphTransient(LazyRatsParser.java:879)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pParagraphMemoized$1(LazyRatsParser.java:826)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pParagraphMemoized(LazyRatsParser.java:812)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pParagraph(LazyRatsParser.java:777)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pBlock(LazyRatsParser.java:531)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pBlockContent(LazyRatsParser.java:462)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pSectionContentStar(LazyRatsParser.java:5588)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pSection(LazyRatsParser.java:5309)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pSectionsTransient(LazyRatsParser.java:5240)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pSectionsMemoized$1(LazyRatsParser.java:5193)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pSectionsMemoized(LazyRatsParser.java:5179)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pSections(LazyRatsParser.java:5144)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pLineStartProd(LazyRatsParser.java:744)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pParagraphStopper(LazyRatsParser.java:985)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.p$$Shared1(LazyRatsParser.java:1129)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pPostParaWs(LazyRatsParser.java:1311)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pParagraphTransient(LazyRatsParser.java:937)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pParagraphMemoized$1(LazyRatsParser.java:826)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pParagraphMemoized(LazyRatsParser.java:812)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pParagraph(LazyRatsParser.java:777)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pBlock(LazyRatsParser.java:531)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pBolBlockContent(LazyRatsParser.java:412)
    at org.sweble.wikitext.lazy.parser.LazyRatsParser.pArticle(LazyRatsParser.java:168)
    at org.sweble.wikitext.lazy.LazyParser.parseArticle(LazyParser.java:76)
    at org.sweble.wikitext.engine.Compiler.parse(Compiler.java:661)
    ... 16 more

```

Related to (closed & duplicate issue) https://github.com/dkpro/dkpro-jwpl/issues/156
