### ISSUE TITLE
Database import yields ConfigurationException

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-jwpl#98]
Originally reported on Google Code with ID 104

```
What steps will reproduce the problem?
1. Use ConfigGUI and activate direct database import.
2. Specify valid database parameters.
3. Specify other necessary parameters as usual.
4. Save the configuration and start the import using the DiffTool.

What is the expected output? What do you see instead?

java.lang.RuntimeException: de.tudarmstadt.ukp.wikipedia.revisionmachine.common.exceptions.ConfigurationException:
CONFIGURATION_CONFIGURATIONMANAGER_UNKNOWN_CONFIG_PARAMETER:
SQL_HOST
    at de.tudarmstadt.ukp.wikipedia.revisionmachine.difftool.DiffToolThread.run(DiffToolThread.java:374)
    at de.tudarmstadt.ukp.wikipedia.revisionmachine.difftool.DiffTool.main(DiffTool.java:56)
    at CreateRevisionDatabase.main(CreateRevisionDatabase.java:11)
Caused by: de.tudarmstadt.ukp.wikipedia.revisionmachine.common.exceptions.ConfigurationException:
CONFIGURATION_CONFIGURATIONMANAGER_UNKNOWN_CONFIG_PARAMETER:
SQL_HOST
    at de.tudarmstadt.ukp.wikipedia.revisionmachine.common.exceptions.ErrorFactory.createConfigurationException(ErrorFactory.java:100)
    at de.tudarmstadt.ukp.wikipedia.revisionmachine.difftool.config.ConfigurationManager.getConfigParameter(ConfigurationManager.java:137)
    at de.tudarmstadt.ukp.wikipedia.revisionmachine.difftool.consumer.dump.writer.SQLDatabaseWriter.<init>(SQLDatabaseWriter.java:80)
    at de.tudarmstadt.ukp.wikipedia.revisionmachine.difftool.DiffToolThread$TaskTransmitter.<init>(DiffToolThread.java:195)
    at de.tudarmstadt.ukp.wikipedia.revisionmachine.difftool.DiffToolThread.run(DiffToolThread.java:284)
    ... 2 more


What version of the product are you using? On what operating system?
0.9.2; Linux

Please provide any additional information below.

```

Reported by `chmeyer.de` on 2012-10-29 10:29:15

**Comment by rzo1** [comment]
Not reproducable with current version of JWPL. Closing.
